### ISSUE TITLE
Question about Test-RegSeg dataset and Hyperparameters

### ISSUE THREAD

**Issue by hatanakashumpei** [kanji95/Talk2car-Refseg#1]
Hi, thanks for your great dataset!

Recently, I have been trying to conduct research using the Talk2Car-RefSeg(https://github.com/kanji95/Talk2car-Refseg) dataset with its provided code. However, I met some trouble as follows:

- In the Test-RegSeg (https://github.com/kanji95/Talk2car-Refseg/blob/main/dataloader/talk2car_test.json) dataset, it seems that the annotations of the image and command are not match. We tried but couldn’t obtain the same evaluation results as in the paper. For example, for “img_test_10.jpg”, the command refers to "stop behind the red car" but actually,  the red car is not shown in the image. We found several samples in this case.
![img_test_10](https://user-images.githubusercontent.com/63159866/195547623-8ff47567-e98c-486e-9c29-29eaf1f94fa0.jpg)
- It is difficult to reproduce the proposed method because some of the model’s hyperparameters are not provided in the paper. For example, the number of layers of the Transformer Decoder is not given.

So, we would appreciate it if you could share the Test-RegSeg dataset (as well as json file) used in the paper and more information about the hyperparameters used in the experiments.

**Comment by kanji1011** [comment]
Hi, thank you for pointing out the issues. I have corrected them.
